image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 7.0.4-debian-11-r2
  digest: ""
  pullPolicy: IfNotPresent

architecture: replicaset

auth:
  enabled: true
  rootUser: root

replicaSetName: rs0

configuration: |-
  # where and how to store data.
  storage:
    dbPath: /bitnami/mongodb/data/db
    wiredTiger:
      engineConfig:
        cacheSizeGB: 8
        journalCompressor: snappy
    directoryPerDB: false

  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0

  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
    #bindIp:

  # replica set options
  replication:
    replSetName: rs0
    oplogSizeMB: 8192
    enableMajorityReadConcern: true

  # sharding options
  #sharding:
    #clusterRole:

  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: false

  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile

replicaCount: 3

affinity: {}

persistence:
  enabled: true
  storageClass: "local-storage"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  mountPath: /bitnami/mongodb

serviceAccount:

  create: true

rbac:
  create: true

arbiter:
  enabled: true
  configuration: ""