
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer
  namespace: apps
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
